# Generated by Django 4.2 on 2024-07-22 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productprice',
            options={'ordering': ['-issue_date', 'product'], 'verbose_name': 'Precio de Producto', 'verbose_name_plural': 'Precios de Productos'},
        ),
        migrations.AddField(
            model_name='productprice',
            name='state',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='category',
            field=models.ManyToManyField(related_name='product_prices', to='core.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='issue_date',
            field=models.DateField(verbose_name='Fecha de emisión'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_prices', to='core.line', verbose_name='Línea'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.product', verbose_name='Producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productprice',
            name='type_increment',
            field=models.CharField(choices=[('P', 'Porcentaje'), ('V', 'Valor')], max_length=1, verbose_name='Tipo de incremento'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
