# Generated by Django 4.2 on 2024-07-22 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_productprice_options_productprice_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_prices', to='core.line', verbose_name='Línea'),
        ),
    ]
