# Generated by Django 4.2 on 2024-07-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
    ]
