# Generated by Django 4.2 on 2024-07-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customer_email_alter_customer_gender_and_more'),
    ]

    migrations.AlterField(
        model_name='customer',
        name='latitude',
        field=models.DecimalField(max_digits=9, decimal_places=6, default=0),
    ),
